### ISSUE TITLE
Can this support ssd_mobilenet_v2_coco?

### ISSUE THREAD

**Issue by FreedomTrail** [borongyuan/ssd_ros#1]
If don't modify config.py and uffssd.cpp in this repository, Can it support ssd_mobilenet_**v2**_coco?

**Comment by borongyuan** [comment]
Yes, but you need to export the pb file using TensorFlow Object Detection API v1.8. It may not work with other version of TensorFlow Models. I use mobilenet v1 because it is faster on GPU.

**Comment by FreedomTrail** [comment]
Thanks,I will try.

**Comment by FreedomTrail** [comment]
> Yes, but you need to export the pb file using TensorFlow Object Detection API v1.8. It may not work with other version of TensorFlow Models. I use mobilenet v1 because it is faster on GPU.

Thanks,I will try.

**Comment by FreedomTrail** [comment]
> Yes, but you need to export the pb file using TensorFlow Object Detection API v1.8. It may not work with other version of TensorFlow Models. I use mobilenet v1 because it is faster on GPU.

nvidia@nvidia-desktop:/usr/src/tensorrt/samples/sampleUffSSD$ sudo make
[sudo] password for nvidia: 
../Makefile.config:7: CUDA_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDA_INSTALL_DIR=<cuda_directory> to change.
../Makefile.config:10: CUDNN_INSTALL_DIR variable is not specified, using $CUDA_INSTALL_DIR by default, use CUDNN_INSTALL_DIR=<cudnn_directory> to change.
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/dchobj/../common; fi; :
Compiling: sampleUffSSD.cpp
sampleUffSSD.cpp:21:15: error: ‘gLogger’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static Logger gLogger;
               ^~~~~~~
In file included from BatchStreamPPM.h:58:0,
                 from sampleUffSSD.cpp:12:
../common/logger.h:55:15: note: previous declaration of ‘gLogger’
 extern Logger gLogger;
               ^~~~~~~
sampleUffSSD.cpp: In function ‘int main(int, char**)’:
sampleUffSSD.cpp:536:5: error: ‘Int8EntropyCalibrator’ was not declared in this scope
     Int8EntropyCalibrator calibrator(calibrationStream, FIRST_CAL_BATCH, "CalibrationTableSSD");
     ^~~~~~~~~~~~~~~~~~~~~
sampleUffSSD.cpp:538:85: error: ‘calibrator’ was not declared in this scope
  tmpEngine = loadModelAndCreateEngine(fileName.c_str(), N, parser, &calibrator, trtModelStream);
                                                                     ^~~~~~~~~~
../Makefile.config:173: recipe for target '../../bin/dchobj/sampleUffSSD.o' failed
make: *** [../../bin/dchobj/sampleUffSSD.o] Error 1

**When I execute step5 to compile mobilenet_v1 to get .plan, i got this error.  can help me?**
**My device:TX2
TensorRT:5.1.6.1**

**Comment by borongyuan** [comment]
Did you successfully compiled the original sampleUffSSD.cpp in TensorRT samples? The published code was only tested with TensorRT 5.0.2. I've also implemented ssd_ros for TensorRT 4 before. There is significant difference between sample code in TensorRT 4 and TensorRT 5.0. I'm not sure if they have made other changes in TensorRT 5.1.
I suggest to remodify the original sampleUffSSD.cpp in TensorRT 5.1. There are just few changes.
1.Replace
`trtModelStream = engine->serialize();`
with
`ofstream planFile;
planFile.open("sample_ssd.plan");
trtModelStream = engine->serialize();
planFile.write((char *)trtModelStream->data(), trtModelStream->size());
planFile.close();`
2.Replace
`builder->setHalf2Mode(false);`
with
`builder->setFp16Mode(true);`
3.set N (batch_size) to 1

**Comment by borongyuan** [comment]
Here is the Demo of mobilenet_v2_oid
https://www.youtube.com/watch?v=2AbEOLF0Buw
