### ISSUE TITLE
How to input a data?

### ISSUE THREAD

**Issue by FreedomTrail** [borongyuan/ssd_ros#2]
I have another question,How to input a data?

**Comment by borongyuan** [comment]
This Node or Nodelet subscribesstandard ROS image msg and convert to cv::Mat. Then it was converted to tensor using cvImageToTensor in utils.h.

**Comment by FreedomTrail** [comment]
> This Node or Nodelet subscribesstandard ROS image msg and convert to cv::Mat. Then it was converted to tensor using cvImageToTensor in utils.h.

emm...This means I should install a usb camera on my TX2???Can I input data with images?

**Comment by borongyuan** [comment]
This is a ROS package for real time object detection in robotics. For image input, you could just use the original sampleuffssd in tensorrt samples.

**Comment by FreedomTrail** [comment]
> This is a ROS package for real time object detection in robotics. For image input, you could just use the original sampleuffssd in tensorrt samples.

In this repository method,Should I launch the ROS node 'image_publisher' with a new terminal?

**Comment by FreedomTrail** [comment]
nvidia@nvidia-desktop:~$ rosrun image_publisher image_publisher __name:=image_publisher /home/nvidia/ros_ws/data/images/person.jpg
[ INFO] [1574047781.747610728]: File name for publishing image is : /home/nvidia/ros_ws/data/images/person.jpg
[ INFO] [1574047781.763228670]: Flip horizontal image is : false
[ INFO] [1574047781.764500989]: Flip flip_vertical image is : false

=========================================================================

nvidia@nvidia-desktop:~$ roslaunch ssd_ros ssd_infer.launch 
... logging to /home/nvidia/.ros/log/a2ad749c-09b3-11ea-b9c3-7af7e2124c61/roslaunch-nvidia-desktop-16922.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nvidia-desktop:32939/

SUMMARY

========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /ssd_infer/label_filename: /home/nvidia/catk...
 * /ssd_infer/num_classes: 91
 * /ssd_infer/plan_filename: /home/nvidia/catk...
 * /ssd_infer/visualize_threshold: 0.5

NODES
  /
    ssd_infer (ssd_ros/ssd_node)

ROS_MASTER_URI=http://localhost:11311

process[ssd_infer-1]: started with pid [16939]
[ INFO] [1574047810.669825290]: [[trt_infer.cu]] Plugin Creator registration succeeded - GridAnchor_TRT
[ INFO] [1574047810.673173000]: [[trt_infer.cu]] Plugin Creator registration succeeded - NMS_TRT
[ INFO] [1574047810.673524040]: [[trt_infer.cu]] Plugin Creator registration succeeded - Reorg_TRT
[ INFO] [1574047810.673747976]: [[trt_infer.cu]] Plugin Creator registration succeeded - Region_TRT
[ INFO] [1574047810.673956392]: [[trt_infer.cu]] Plugin Creator registration succeeded - Clip_TRT
[ INFO] [1574047810.674182343]: [[trt_infer.cu]] Plugin Creator registration succeeded - LReLU_TRT
[ INFO] [1574047810.674434151]: [[trt_infer.cu]] Plugin Creator registration succeeded - PriorBox_TRT
[ INFO] [1574047810.674742247]: [[trt_infer.cu]] Plugin Creator registration succeeded - Normalize_TRT
[ INFO] [1574047810.675169447]: [[trt_infer.cu]] Plugin Creator registration succeeded - RPROI_TRT
[ INFO] [1574047810.675521159]: [[trt_infer.cu]] Plugin Creator registration succeeded - BatchedNMS_TRT
[ INFO] [1574047810.675763815]: Begin loading plan...
[ INFO] [1574047810.800531267]: *** deserializing
ssd_node: /home/nvidia/ros_ws/src/ssd_ros/src/trt_infer.cu:66: FlattenConcat::FlattenConcat(const void*, size_t): Assertion `mConcatAxisID == 1 || mConcatAxisID == 2 || mConcatAxisID == 3' failed.
[ssd_infer-1] process has died [pid 16939, exit code -6, cmd /home/nvidia/ros_ws/devel/lib/ssd_ros/ssd_node /ssd_infer/input_topic:=/camera/color/image_raw /ssd_infer/output_topic:=/ssd_infer/bounding_boxes __name:=ssd_infer __log:=/home/nvidia/.ros/log/a2ad749c-09b3-11ea-b9c3-7af7e2124c61/ssd_infer-1.log].
log file: /home/nvidia/.ros/log/a2ad749c-09b3-11ea-b9c3-7af7e2124c61/ssd_infer-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Hi, I published an image by running image_publisher, then I launched  ssd_infer.launch,I got this error.**

**Comment by borongyuan** [comment]
It seems that you have successfully converted a model to a serialized engine. But it failed to deserialize. You may also need to modify trt_infer.cu, because the classes are copied from sampleUffSSD.cpp in TensorRT 5.0 samples.

**Comment by FreedomTrail** [comment]
**Did you convert pb to uff with this command:**
**python convert_to_uff frozen_inference_graph.pb -O NMS -p config.py?**

**I found when I parsed uff model to get the .plan file,It had got this error:**
nvidia@nvidia-desktop:/usr/src/tensorrt/bin$ ./sample_uff_ssd
&&&& RUNNING TensorRT.sample_uff_ssd # ./sample_uff_ssd
[I] ../data/ssd/sample_ssd_relu6.uff
[I] Begin parsing model...
sample_uff_ssd: sampleUffSSD.cpp:294: FlattenConcat::FlattenConcat(int, bool): Assertion `mConcatAxisID == 1 || mConcatAxisID == 2 || mConcatAxisID == 3' failed.
Aborted (core dumped)

**Comment by FreedomTrail** [comment]
Hi,When I executed :  **rostopic echo /ssd_infer/bounding_boxes** , I have successfully got the output.
- 
    object: 
      object_name: "person"
      probability: 0.995037019253
    roi: 
      x_offset: 186
      y_offset: 99
      height: 274
      width: 84
      do_rectify: False
  - 
    object: 
      object_name: "dog"
      probability: 0.608594059944
    roi: 
      x_offset: 65
      y_offset: 264
      height: 90
      width: 139
      do_rectify: False
inference_time_ms: 21.5966911316


**Thank you very much.!
I have only one question is that when I launch ssd_viewer.launch,  I did't get the output, can you give some clue? thanks.**

**Comment by borongyuan** [comment]
I think you may subscribe to different topics. Use `rostopic list` to check which topic the infer is publishing and which topic the viewer is subscribing. You may need to remap topics or modify the launch file.
Another possibility is due to sync mechanism of the viewer. I'm not sure if your image topics have time stamp in header. The vierer only handles data (image & inference result) which have the same time stamp.

**Comment by FreedomTrail** [comment]
> I think you may subscribe to different topics. Use `rostopic list` to check which topic the infer is publishing and which topic the viewer is subscribing. You may need to remap topics or modify the launch file.
> Another possibility is due to sync mechanism of the viewer. I'm not sure if your image topics have time stamp in header. The vierer only handles data (image & inference result) which have the same time stamp.

Haha, Thank you very much, I got it!!!
